version: "3.8"

services:
  postgres:
    image: postgres
    container_name: postgres-dbs
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_MULTIPLE_DATABASES: postgres:agents,postgres:tasks,postgres:data,postgres:metadata,postgres:users
    volumes:
      - ./.vol/pg-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"

  cnc-cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PSWD}
    volumes:
      - ./.cache:/redis_data

  cnc-service:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./cnc:/app/cnc
      - ./.env:/app/.env
    command: ./.venv/bin/uvicorn cnc.app:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - postgres
      - cnc-cache
