services:
  postgres:
    image: postgres
    container_name: postgres-dbs
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_MULTIPLE_DATABASES: postgres:agents,postgres:tasks,postgres:data
    volumes:
      - ./.vol/pg-data:/var/lib/postgresql/data
#      - ./dbs_config:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"

#  nginx-server:
#    container_name: nginx_server
#    image: nginx
#    ports:
#      - "8001:80"
