[project]
name = "cnc"
version = "0.1.0"
description = "Command & control panel"
authors = ["Yechiel Babani <yechielb2000@gmail.com>"]
dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "httpx",
    "sqlalchemy",
    "pydantic",
    "elasticsearch",
]

[tool.uv.workspace]
members = [
    "/cnc/cnc-core",
    "/cnc/data-parser",
    "/cnc/data-receiver",
    "/cnc/task-provider",
    "/ui/backend"
]
