[project]
name = "cnc-gateway"
version = "0.1.0"
description = "Simple cnc gateway"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.12.13",
    "fastapi>=0.115.12",
    "redis>=6.0.0",
    "slowapi>=0.1.9",
    "uvicorn>=0.34.2",
]
